### ISSUE TITLE
Label cleanup

### ISSUE THREAD

**Issue by colinmegill** [FormidableLabs/victory-axis#10]
- [ ] Make font size a function of how many characters the number / word is 
- [ ] ~~http://stackoverflow.com/questions/18151877/javascript-shorten-large-numbers-force-decimal-places-and-choose-to-represent~~
- [ ] ~~truncate decimal places when zeros~~
- [x] support multi-line labels

**Comment by boygirl** [comment]
"truncate decimal places when zeros", and force decimal places seem like they should be the concern of the user configurable `tickFormat` prop (takes a function or an array)
