### ISSUE TITLE
animating axis ticks looks crazy

### ISSUE THREAD

**Issue by boygirl** [FormidableLabs/victory-axis#8]
getting automatic ticks from a domain / scale results in an inconsistent number of ticks.  See https://github.com/mbostock/d3/wiki/Quantitative-Scales#linear_ticks

this means that the ticks and their grid lines pop in and out of existence during the animation, and look very, very broken

**Comment by coopy** [comment]
This wold be solved by https://github.com/FormidableLabs/victory-animation/issues/28

**Comment by boygirl** [comment]
closing as a duplicate of https://github.com/FormidableLabs/victory-chart/issues/4
